# Version du langage docker-compose à utiliser :
version: "3"

services:
    lamp:
            container_name: PHP8.1
            restart: always

            # Permet de démarrer à partir d'un dockerfile au lieu d'une image
            build:
                context: ./
                dockerfile: "Dockerfile"

            #volumes:
            #- /home/david/www/local.sbs/:/app/

            ports:
            - "86:80"
